### ISSUE TITLE
Not able to run agent with Ollama llama3.2 model locally "Could not parse response."

### ISSUE THREAD

**Issue by AceCodePt** [browser-use/browser-use#220]
Hi :)
As sorta of continuation to #173 
Ran locally with:
```toml
[project]
name = "check"
version = "0.1.0"
description = ""
authors = [
    {name = "Sagi Carmel",email = "ace.code.pt@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "asyncio (>=3.4.3,<4.0.0)",
    "browser-use (>=0.1.19,<0.2.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "playwright (>=1.49.1,<2.0.0)",
    "langchain-ollama (>=0.2.2,<0.3.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
``` 

```sh
poetry run ./check/main.py
```

wth:
```py
#!/usr/bin/env python
"""
Simple try of the agent.
"""

import asyncio

from langchain_ollama import ChatOllama

from browser_use import Agent
# from browser_use.browser.browser import Browser, BrowserConfig

from dotenv import load_dotenv
load_dotenv()

# browser = Browser(
# 	config=BrowserConfig(
# 		headless=False,
# 		cdp_url="http://localhost:9222",
# 	)
# )

async def run_search() -> str:
    agent = Agent(
        task="Search for a 'browser use' post on the r/LocalLLaMA subreddit and open it.",
        llm=ChatOllama(
            model="llama3.2",
            num_ctx=32000,
        ),
    )

    result = await agent.run()
    return result


async def main():
    result = await run_search()
    print("\n\n", result)


if __name__ == "__main__":
    asyncio.run(main())

```

Still getting this result:
![image](https://github.com/user-attachments/assets/c1b1cdf2-3b8e-4d2a-b87b-2c66dce00035)

The poetry is 0.1.19:
![image](https://github.com/user-attachments/assets/fea1168f-50e1-4650-9513-35abcac36ae1)
